name : Update-UPM-Branch

# v1.2.3 같은 태그가 푸시되면 시작 
on : 
  workflow_dispatch:
  push : 
    tags : 
      - v*
jobs :
  update :
    runs-on : ubuntu-latest
    steps:
      # 최신 가져오기
       - name : Checkout
         uses: actions/checkout@v2
         with:
          fetch-depth: 0
       # 이벤트를 시작한 태그를 steps.tag.outputs.name에 저장 
       - name: Tag name
         id: tag
         run: |
          if [ -z "${{ GITHUB_REF#refs/tags/ }}" ]; then
            echo "The tag does not exist"
            echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"
          else
            echo "The tag exists"
            echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/v}"
          fi
         
       - name: Create UPM Branch
         uses: kangHeeAh/create-upm-branch-action@main
         with:
          git-tag: ${{ steps.tag_name.outputs.tag_name }}
          pkg-root-dir-path: Assets/com.test.upm
          main-branch: main
