name: Update-UPM-Branch

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to update the UPM branch'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tag name
        id: tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "::set-output name=name::${{ github.event.inputs.tag }}"

      - name: Check if tag exists
        id: check_tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if ! git rev-parse -q --verify "refs/tags/${{ steps.tag.outputs.name }}" >/dev/null; then
            echo "Tag '${{ steps.tag.outputs.name }}' does not exist."
            exit 1
          fi

      - name: Create UPM Branch
        uses: kangHeeAh/create-upm-branch-action@main
        with:
          git-tag: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref.replace('refs/tags/', '') || steps.tag.outputs.name }}
          pkg-root-dir-path: Assets/com.test.upm
          main-branch: master
